// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: rshard.proto

package rshardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record string `protobuf:"bytes,1,opt,name=Record,proto3" json:"Record,omitempty"`
	Color  int64  `protobuf:"varint,2,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rshard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rshard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_rshard_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *AppendRequest) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

type CommittedRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn    int64  `protobuf:"varint,1,opt,name=Gsn,proto3" json:"Gsn,omitempty"`
	Record string `protobuf:"bytes,2,opt,name=Record,proto3" json:"Record,omitempty"`
	Color  int64  `protobuf:"varint,3,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *CommittedRecord) Reset() {
	*x = CommittedRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rshard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommittedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedRecord) ProtoMessage() {}

func (x *CommittedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rshard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedRecord.ProtoReflect.Descriptor instead.
func (*CommittedRecord) Descriptor() ([]byte, []int) {
	return file_rshard_proto_rawDescGZIP(), []int{1}
}

func (x *CommittedRecord) GetGsn() int64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

func (x *CommittedRecord) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *CommittedRecord) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn   int64 `protobuf:"varint,1,opt,name=Gsn,proto3" json:"Gsn,omitempty"`
	Color int64 `protobuf:"varint,2,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rshard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rshard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_rshard_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetGsn() int64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

func (x *ReadRequest) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_rshard_proto protoreflect.FileDescriptor

var file_rshard_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x72, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x51, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x73,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x47, 0x73, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x0b, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x73, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x47, 0x73, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x32, 0x8c, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x12, 0x3c, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x17, 0x2e, 0x72, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x3f, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x15, 0x2e, 0x72,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x30, 0x01,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x61, 0x74, 0x68, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x77, 0x2f, 0x6f,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x6f, 0x6e, 0x2f, 0x72, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2f, 0x72,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rshard_proto_rawDescOnce sync.Once
	file_rshard_proto_rawDescData = file_rshard_proto_rawDesc
)

func file_rshard_proto_rawDescGZIP() []byte {
	file_rshard_proto_rawDescOnce.Do(func() {
		file_rshard_proto_rawDescData = protoimpl.X.CompressGZIP(file_rshard_proto_rawDescData)
	})
	return file_rshard_proto_rawDescData
}

var file_rshard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rshard_proto_goTypes = []interface{}{
	(*AppendRequest)(nil),   // 0: rshardpb.AppendRequest
	(*CommittedRecord)(nil), // 1: rshardpb.CommittedRecord
	(*ReadRequest)(nil),     // 2: rshardpb.ReadRequest
}
var file_rshard_proto_depIdxs = []int32{
	0, // 0: rshardpb.RecordShard.Append:input_type -> rshardpb.AppendRequest
	2, // 1: rshardpb.RecordShard.Subscribe:input_type -> rshardpb.ReadRequest
	1, // 2: rshardpb.RecordShard.Append:output_type -> rshardpb.CommittedRecord
	1, // 3: rshardpb.RecordShard.Subscribe:output_type -> rshardpb.CommittedRecord
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rshard_proto_init() }
func file_rshard_proto_init() {
	if File_rshard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rshard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rshard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommittedRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rshard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rshard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rshard_proto_goTypes,
		DependencyIndexes: file_rshard_proto_depIdxs,
		MessageInfos:      file_rshard_proto_msgTypes,
	}.Build()
	File_rshard_proto = out.File
	file_rshard_proto_rawDesc = nil
	file_rshard_proto_goTypes = nil
	file_rshard_proto_depIdxs = nil
}
