// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: shard.proto

package seqshardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumOfRecords int64 `protobuf:"varint,1,opt,name=NumOfRecords,proto3" json:"NumOfRecords,omitempty"`
	StartLsn     int64 `protobuf:"varint,2,opt,name=StartLsn,proto3" json:"StartLsn,omitempty"`
	Color        int64 `protobuf:"varint,3,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetNumOfRecords() int64 {
	if x != nil {
		return x.NumOfRecords
	}
	return 0
}

func (x *OrderRequest) GetStartLsn() int64 {
	if x != nil {
		return x.StartLsn
	}
	return 0
}

func (x *OrderRequest) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartGsn     int64 `protobuf:"varint,1,opt,name=StartGsn,proto3" json:"StartGsn,omitempty"`
	StartLsn     int64 `protobuf:"varint,2,opt,name=StartLsn,proto3" json:"StartLsn,omitempty"`
	NumOfRecords int64 `protobuf:"varint,3,opt,name=NumOfRecords,proto3" json:"NumOfRecords,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetStartGsn() int64 {
	if x != nil {
		return x.StartGsn
	}
	return 0
}

func (x *OrderResponse) GetStartLsn() int64 {
	if x != nil {
		return x.StartLsn
	}
	return 0
}

func (x *OrderResponse) GetNumOfRecords() int64 {
	if x != nil {
		return x.NumOfRecords
	}
	return 0
}

type CommittedRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn    int64  `protobuf:"varint,1,opt,name=Gsn,proto3" json:"Gsn,omitempty"`
	Record string `protobuf:"bytes,2,opt,name=Record,proto3" json:"Record,omitempty"`
}

func (x *CommittedRecord) Reset() {
	*x = CommittedRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommittedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedRecord) ProtoMessage() {}

func (x *CommittedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedRecord.ProtoReflect.Descriptor instead.
func (*CommittedRecord) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{2}
}

func (x *CommittedRecord) GetGsn() int64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

func (x *CommittedRecord) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

var File_shard_proto protoreflect.FileDescriptor

var file_shard_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x22, 0x64, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4e,
	0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4c, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4c, 0x73, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x6b, 0x0a,
	0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x73, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4c, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4c, 0x73, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4e, 0x75,
	0x6d, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x47, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x47, 0x73, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x32, 0x9c, 0x01, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x2e,
	0x73, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x52, 0x0a, 0x16, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x19, 0x2e, 0x73,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x19, 0x2e, 0x73, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x28, 0x01, 0x30, 0x01, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x74, 0x68, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x74, 0x6f,
	0x72, 0x6e, 0x6f, 0x77, 0x2f, 0x6f, 0x73, 0x74, 0x72, 0x61, 0x63, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x71, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2f, 0x73, 0x65, 0x71, 0x73, 0x68, 0x61, 0x72, 0x64, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shard_proto_rawDescOnce sync.Once
	file_shard_proto_rawDescData = file_shard_proto_rawDesc
)

func file_shard_proto_rawDescGZIP() []byte {
	file_shard_proto_rawDescOnce.Do(func() {
		file_shard_proto_rawDescData = protoimpl.X.CompressGZIP(file_shard_proto_rawDescData)
	})
	return file_shard_proto_rawDescData
}

var file_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shard_proto_goTypes = []interface{}{
	(*OrderRequest)(nil),    // 0: sshardpb.OrderRequest
	(*OrderResponse)(nil),   // 1: sshardpb.OrderResponse
	(*CommittedRecord)(nil), // 2: sshardpb.CommittedRecord
}
var file_shard_proto_depIdxs = []int32{
	0, // 0: sshardpb.Shard.GetOrder:input_type -> sshardpb.OrderRequest
	2, // 1: sshardpb.Shard.ReportCommittedRecords:input_type -> sshardpb.CommittedRecord
	1, // 2: sshardpb.Shard.GetOrder:output_type -> sshardpb.OrderResponse
	2, // 3: sshardpb.Shard.ReportCommittedRecords:output_type -> sshardpb.CommittedRecord
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shard_proto_init() }
func file_shard_proto_init() {
	if File_shard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommittedRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shard_proto_goTypes,
		DependencyIndexes: file_shard_proto_depIdxs,
		MessageInfos:      file_shard_proto_msgTypes,
	}.Build()
	File_shard_proto = out.File
	file_shard_proto_rawDesc = nil
	file_shard_proto_goTypes = nil
	file_shard_proto_depIdxs = nil
}
